### ISSUE TITLE
Purpose of initial knitting step

### ISSUE THREAD

**Issue by stoyelq** [inSileco/shinySpatialApp_origin#26]
The render_full_report function initially knitted the report before rendering it, as two steps.  This was successful in generating reports, but broke a lot of the formatting, particularly around figures and captions, so I switched it to only a single render step.  

Do you remember the particular advantage of knitting the report as a separate step (was it to speed up rendering to multiple formats?) and/or how to fix the formatting issues?  

I don't necessarily expect a fix here, feel free to just comment/reply to this issue if that's easiest.

**Comment by KevCaz** [comment]
@stoyelq I remember why! 

I did this so that at the end of the process, the Rmd file includes all the text. Currently, with your changes the Rmd downloaded (when clicking on "Download outputs") cannot be used as the child Rmd documents are not included in the zip (they were in the previous version). I guess I thought it would make more sense to have everything in one document. 

Let me know what you think!

I think there are 3 options:
1. Remove the Rmd document 
2. Add all child Rmd documents in the zip file 
3. Try to go back to what I did and try to figure out why it does not work (a simple option could be to do an extra rendering as a Markdown document, which is basically what I was trying to do)

**Comment by stoyelq** [comment]
Yes, it makes sense to avoid having child sections in the output RMD!  Removing the rmd from the download is probably best.  Between the search area and the html in the output file, reproducing the report should not be a problem.

**Comment by KevCaz** [comment]
@stoyelq, just to be sure we're on the same page. I let the current render process as it is, and I simply remove the Rmd from the set of outputs to be downloaded.

**Comment by stoyelq** [comment]
@KevCaz, yes, that is correct.
